<?php


namespace backend\models;


use yii\db\ActiveRecord;

/**
 * Class Cities
 * @package backend\models
 * @property int $id [int(11)]
 * @property int $state_id [int(11)]
 * @property string $title [varchar(255)]
 * @property States $state
 * @property string $zip_code [varchar(255)]
 */

class Cities extends ActiveRecord
{
    public static function tableName()
    {
        return 'cities'; // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [
                [
                    'state_id', 'title'
                ], 'required'
            ],
            [
                [
                    'state_id'
                ], 'integer'
            ],
            [
                [
                    'title', 'zip_code'
                ], 'string'
            ]
        ];
    }

    public function attributeLabels()
    {
        return [
            'state_id' => 'State'
        ];
    }

    public function getState() {
        return $this->hasOne(States::class, ['id' => 'state_id']);
    }

}