<?php


namespace backend\models;


use yii\db\ActiveRecord;

/**
 * Class MoveTypes
 * @package backend\models
 * @property int $id [int(11)]
 * @property string $title [varchar(255)]
 */

class MoveTypes extends ActiveRecord
{
    public function rules()
    {
        return [
            [
                [
                    'title'
                ], 'string'
            ],
            [
                [
                    'title'
                ], 'required'
            ],
            [
                [
                    'id'
                ], 'safe'
            ]
        ]; // TODO: Change the autogenerated stub
    }

    public static function tableName()
    {
        return 'move_types'; // TODO: Change the autogenerated stub
    }
}