<?php


namespace backend\models;


use yii\db\ActiveRecord;

class SettingsImages extends ActiveRecord
{
    public static function tableName()
    {
        return 'settings_images';
    }
    public function rules()
    {
        return [
            [[
                'about_us_image', 'our_service_1', 'our_service_2',
                'our_service_3', 'comment_section_image'
                ], 'required']
        ]; // TODO: Change the autogenerated stub
    }
}