<?php


namespace backend\models;


use yii\db\ActiveRecord;

class SettingsText extends ActiveRecord
{
    public static function tableName()
    {
        return 'settings_text'; // TODO: Change the autogenerated stub
    }
    public function rules()
    {
        return [
            [[
                'call_us_number', 'about_us', 'one_tick_header',
                'two_tick_header', 'three_tick_header', 'four_tick_header',
                'five_tick_header', 'six_tick_header', 'one_tick_content',
                'two_tick_content', 'three_tick_content', 'four_tick_content',
                'five_tick_content', 'six_tick_content'
            ], 'required']
        ];
    }
}