<?php


namespace backend\models;


use yii\db\ActiveRecord;

/**
 * Class States
 * @package backend\models
 * @property int $id [int(11)]
 * @property string $title [varchar(255)]
 */

class States extends ActiveRecord
{
    public static function tableName()
    {
        return 'states'; // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [
                [
                    'title'
                ], 'string'
            ],
            [
                [
                    'title'
                ], 'required'
            ],
            [
                [
                    'id'
                ], 'safe'
            ]
        ]; // TODO: Change the autogenerated stub
    }

    public function getCities() {
        return $this->hasMany(Cities::class, ['state_id' => 'id']);
    }
}